# Generated by Django 3.1.4 on 2021-06-16 16:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUUIDModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MRepository',
            fields=[
                ('myuuidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipe_hub.myuuidmodel')),
                ('id_fork_from', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=8192)),
                ('recipe', models.CharField(max_length=16384)),
                ('id_author', models.CharField(max_length=36)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=('recipe_hub.myuuidmodel',),
        ),
        migrations.CreateModel(
            name='MUser',
            fields=[
                ('myuuidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipe_hub.myuuidmodel')),
                ('name', models.CharField(max_length=8192)),
                ('password', models.CharField(max_length=8192)),
                ('email', models.EmailField(max_length=254)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=('recipe_hub.myuuidmodel',),
        ),
    ]
