# Generated by Django 3.1.4 on 2021-06-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrepository',
            name='id_fork_from',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
