# Generated by Django 3.1.4 on 2021-06-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_hub', '0003_auto_20210621_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrepository',
            name='id_fork_to_list',
            field=models.CharField(default='', max_length=8192),
        ),
        migrations.AlterField(
            model_name='mrepository',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
