# Generated by Django 3.1.4 on 2021-06-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_hub', '0004_auto_20210621_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrepository',
            name='id_fork_to_list',
            field=models.CharField(default='{}', max_length=8192),
        ),
    ]
