# Generated by Django 3.1.4 on 2021-06-27 19:09

from django.db import migrations, models
import recipe_hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_hub', '0005_auto_20210621_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrepository',
            name='author_photo_url',
            field=models.CharField(default='', max_length=8192),
        ),
        migrations.AlterField(
            model_name='mrepository',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=recipe_hub.models.path_and_rename),
        ),
    ]
