# Generated by Django 3.1.4 on 2021-06-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_hub', '0006_auto_20210627_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrepository',
            name='author_name',
            field=models.CharField(default='', max_length=8192),
        ),
        migrations.AlterField(
            model_name='mrepository',
            name='id_author',
            field=models.CharField(max_length=8192),
        ),
    ]
